### ISSUE TITLE
Update Android Platform Guide to Cordova 9.0

### ISSUE THREAD

**Issue by gghordijk** [apache/cordova-docs#1058]
Hello,

Not sure where to place this request. It doesn't seem a bug or a feature from my point of view.

Could someone update the supported Requirements and Support of Android Platform Guide ([link](https://cordova.apache.org/docs/en/latest/guide/platforms/android/#requirements-and-support)) with the latest Cordova version?

Thanks.

**Comment by brodybits** [comment]
Thanks, I just transferred this issue to cordova-docs.

**Comment by breautek** [comment]
Just a couple of notes...

I believe everything under [Requirements and Support](https://cordova.apache.org/docs/en/latest/guide/platforms/android/#requirements-and-support) is already up to date. Cordova-android@9 is in the works which will be the version to officially support API 22 to 29 (android 5.1 to 10), but that information should only appear in the `dev` version of the docs, not `latest`. (At the time of writing)

Under [Adding SDK Packages](https://cordova.apache.org/docs/en/latest/guide/platforms/android/#adding-sdk-packages) it states:

`Android SDK build-tools version 19.1.0 or higher`

I believe the build tools should actually be, at minimum, the same as the target SDK. So for example, cordova-android@8 by default uses target sdk 28, there build-tools `28.0.0` (at least) is required, so generally saying `19.1.0 or higher` is not right.

And while, `28.0.0` would technically satisfy the android requirements when targeting sdk 28... it doesn't actually satisfy cordova requirements, because [cordova-android@8.1](https://github.com/apache/cordova-android/blob/f1f472297af7d3985a5769edd7272222bfd42416/bin/templates/project/build.gradle#L43) currently looks for build tools `28.0.3`

So I think this information needs to be part of a table that shows what build tools version is required by default, by which version of `cordova-android`

**Comment by breautek** [comment]
Most of what needs to be updated have been either merged in, or will be merged in the near future. The documentation should be much better/accurate starting in the 10.x CLI docs (once it is released).
