### ISSUE TITLE
Android SDK Command-line Tools

### ISSUE THREAD

**Issue by breautek** [apache/cordova-docs#1065]
The android SDK installation guide for [Adding SDK packages](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#adding-sdk-packages) should also mention that "Android SDK Command-line Tools" should be installed.

Newly installed android sdk installations doesn't appear to include some required command line tools without this new SDK tool package, as documented at https://github.com/apache/cordova-android/issues/926#issuecomment-597900281

**Comment by jamesjsewell** [comment]
Could not find either `android` or `avdmanager` on your $PATH! Are you sure the Android SDK is installed and available?
I saw the original issue that was closed. After installing this cli tools im not sure what to do? I don't know the path i should be using for android or for avdmanager? and what that would look like in my bash_profile

**Comment by brodybits** [comment]
> Could not find either `android` or `avdmanager` on your $PATH! Are you sure the Android SDK is installed and available?

That kind of issue is generally supported on Slack (follow link in footer of cordova.io or cordova.apache.org) and StackOverflow, and you need to show the actual output if you are looking for someone to help investigate. We definitely do not want to provide this kind of support in cordova-docs. If you think you really find something wrong with Cordova and not with your environment, please raise a new issue on cordova-android where we can start to look for a solution. (We do not have much time to watch and support closed issues. Most maintainers are overworked volunteers, busy with a new release these days.) The cordova-docs issues are only to identify what is either missing or needs to be fixed in the documentation itself. Thanks.

**Comment by bkmgit** [comment]
It might be helpful to add this information to the documentation since at present there is no option to use command line tools which looks like it will be necessary in future.
