### ISSUE TITLE
Plugin search is not updated 

### ISSUE THREAD

**Issue by ciossi** [apache/cordova-docs#1128]
# Bug Report
Plugin search on Cordova website, at the url https://cordova.apache.org/plugins/,  is not updated. It always shows 5375 plugins from about 2 months.

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Thanks for the hint. It seems the npmsearch.com response could not be parsed

**Comment by breautek** [comment]
> The website npmsearch is down, seemingly permanently

I think this is now a very safe assumption, since npmsearch.com now doesn't have any DNS records. The domain is still registered, just doesn't have any A records anymore.

**Comment by HtmlToAndroid** [comment]
Why hasn't sapient-peartree's suggestion of Oct 22, 2021 been taken up ????
The current situation is **TERRIBLE**

It gives the impression that Cordova is a dead - dead end technology.

> > The website npmsearch is down, seemingly permanently Why not just put up a link for https://www.npmjs.com/search?q=ecosystem%3Acordova for now?
> 
> Would it be possible to direct users of the plugin search page to this search tool, at least temporarily?
> 
> At present there is absolutely no warning that the plugin search page isn't functional or any direction towards any alternatives. Coming to this as a new user of Cordova this was extremely frustrating!
> 
> I'm more than happy to quickly edit the "plugins" html page to throw a quick banner up with words to the effect of the above, if that would help? Only thing is I'm fairly green as a web dev so I can't promise that it'll be overwhelmingly pretty...

**Comment by Zensynthium** [comment]
Though I can't quite say when the plugin search will work again, but I did find this repository of Cordova plugins for use that I'll be attempting to use in my Ionic project.

https://danielsogl.gitbook.io/awesome-cordova-plugins/
https://github.com/danielsogl/awesome-cordova-plugins

**Comment by NiklasMerz** [comment]
This is just a matter of priorities and people volunteering to pick up this issue.

IMHO I don't think a dedicated search for plugins is really necessary. I always just "XZY cordova plugin" with great success. Therefore I suggest that we either remove the page entirely or just put a text there like:

`Cordova plugins are usually distributed by NPM. You can search NPM for plugins for your app or browse it with the ecosystem query:  https://www.npmjs.com/search?q=ecosystem%3Acordova. You can even install plugins directly from Git repositories.`

Maybe we could also add list of all official Apache plugins.

**Comment by breautek** [comment]
> Therefore I suggest that we either remove the page entirely

I think I agree with this sentiment. I've had a look at this issue, looking at the NPM registry API. If we were to have continue having a plugin search, I'd rather use a direct NPM api. The problem is they have the API cors restricted, therefore we'll need to have a proxy server.

Instead of dealing with server hosting that can provide this proxy (and then run into issues like our heroku app issue where we don't even have access to it anymore), I think I'd prefer to replace the plugin search with just a page that explains how plugins are generally distributed.

**Comment by LifeIsStrange** [comment]
I disagree with removing the page entirely as without this github issue I would not have discovered that we could use npm search that way.
The page should simply show a link to the npm search and optionally a guide to plugins and a list of the official ones.

**Comment by breautek** [comment]
> BTW anyone know how to filter for packages that are supported e.g on android AND on ios ?

Generally cordova plugins declare what platforms they support via keywords, which means you can do an NPM search query by doing something like `ecosystem:cordova cordova-android cordova-ios <some other keywords for searching>` to find plugins that supports both cordova-android and cordova-ios.

**Comment by jimwhitfield** [comment]
Is cordova dead?  I'm glad I found this page, but really, someone should either point the search at the url https://cordova.apache.org/plugins/  to something like https://www.npmjs.com/search?q=ecosystem%3Acordova  or remove the search page, which now uses a thoroughly dead search technology.
Since I'm only exploring if Cordova might even meet my needs, I'm not the right person to go mucking with PR's for the cordova site.  (Seeing "no plugins" is a flashing red indicator that it is not, but I'm not that easily dissuaded.)

**Comment by breautek** [comment]
I created a dev discussion thread @ https://lists.apache.org/thread/pz90x2jzlgfblcy9vo7635yqlk4bv6ck so that we can finally reach a final verdict on how we should proceed.

**Comment by LifeIsStrange** [comment]
I don't have an account for this list and since I'm lazy I'll comment here:
I vote for #2 AKA keeping the page but making it have the following layout:
a big link/button to npm search with presupplied arguments including android, ios ecosystems as a logical AND. (since by default I expect people to want cross platform plugins, and it remove them from the burden of finding the exact name of e.g. android tag ecosystem, and removing those terms of the filter query is easy)

the e.g. below the button/link it would be nice to have an noob friendly explainer of the npm search syntax, essentially how to chain logical OR and logical ANDs in the filter query.

then below that explainer there could optionally links to the follwing external lists:
1) official cordova plugins
and 2) community favorite plugins

semi-official:
https://github.com/apache/cordova-plugins
community: (2200 stars)
https://danielsogl.gitbook.io/awesome-cordova-plugins/

as for the alternatives:
a direct redirect instead of a page would be inferior and non-SEO discoverable
a page removal would be non-discoverable "Is cordova dead?"
