### ISSUE TITLE
Plugin API links in inner documentation not working

### ISSUE THREAD

**Issue by ajprok** [apache/cordova-docs#1154]
# Bug Report
Wrong Plugin API links in inner documentation
## Problem
When we click on the documentation link, we are taken to the following page:
[https://cordova.apache.org/docs/en/latest/](https://cordova.apache.org/docs/en/latest/)
In that page, we click on the plugin api links, and we are taken to the appropriate plugin page. Example - on clicking the Battery Status API link we are taken to:
[https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-battery-status/index.html](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-battery-status/index.html)
**However**, in **the plugin API page**, when we click on the plugin api links ....
### What is expected to happen?
We are supposed to go to the correct plugin API link. Example - on clicking the Battery Status API link we are taken to:
[https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-battery-status/index.html](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-battery-status/index.html)
### What does actually happen?
We go to a wrong link which has an extra `/reference/` in its path. Example - on clicking the Battery Status API link we are taken to:
[https://cordova.apache.org/docs/en/latest/reference/reference/cordova-plugin-battery-status/index.html](https://cordova.apache.org/docs/en/latest/reference/reference/cordova-plugin-battery-status/index.html)
## Information
This happens to all the plugin API links.

## Checklist

- [x] I searched for existing GitHub issues

**Comment by breautek** [comment]
Observing this behaviour on all children links when viewing from a child page, not just the plugin api links. As pointed out from: https://github.com/apache/cordova-docs/issues/1157

**Comment by breautek** [comment]
FYI: I believe I have the issue resolved on my local copy, but I'm building the full website locally so that I can test several other pages... and this will take some time. If it goes well, I'll prepare a PR either late tonight or sometime tomorrow night.

I'm not quite sure what broke the links, I'm assuming the jekyll major upgrade from https://github.com/apache/cordova-docs/commit/f6f9ff673c453a348c0a53d30618797fac491920

But the way the website was forming links was dumb imo and backwards... so (hopefully) I improved that logic for the better. We should see soon.

**Comment by breautek** [comment]
Thank you @ajprok for bringing this to our attention.
