### ISSUE TITLE
Update Android Platform Guide to Cordova 10.0

### ISSUE THREAD

**Issue by mcake8** [apache/cordova-docs#1216]
Hello, not sure if that can be classified as a bug

**Requirements and Support** section dosen't have **Supported Android API-Levels** line for cordova **android@10.0.0**

Could someone please update the supported Requirements and Support of Android Platform Guide with the latest Cordova version?

Thanks.

**Comment by breautek** [comment]
The line have been added in our [dev version](https://cordova.apache.org/docs/en/dev/guide/platforms/android/index.html) at some point, just isn't in the released / latest version.

This is because Cordova docs versions are tied to the CLI version, so these changes are generally only published when new CLI versions are released (cordova CLI v10 uses cordova-android 9 by default).

I think one could make a PR to update the 10.x snapshot, but it would have to be manually copied over I think.
