### ISSUE TITLE
Windows docs missing images

### ISSUE THREAD

**Issue by angel-luis** [apache/cordova-docs#953]
# Bug Report

## Problem
Can't see the docs images.

### What is expected to happen?
See images.

### What does actually happen?
Image urls returns 404.

## Information

https://cordova.apache.org/docs/en/latest/guide/platforms/windows/index.html

### Environment, Platform, Device

Web browser.

## Checklist

- [ X ] I searched for existing GitHub issues
- [ X ] I updated all Cordova tooling to most recent version
- [ X ] I included all the necessary information above

**Comment by dblotsky** [comment]
Can confirm: getting the 404. @janpio any ideas why images might be disappearing?

**Comment by erisu** [comment]
@dblotsky Paths has been changed and appears to be because we dropped `win8` from docs `8.x` and newer. `windows` is now the platform name.

Example File Paths:
`https://cordova.apache.org/static/img/guide/platforms/windows/win8_installTools.png`
is now
`https://cordova.apache.org/static/img/guide/platforms/win8/win8_installTools.png`

`win8` was last used in `7.x`. Images still work for this version.
https://cordova.apache.org/docs/en/7.x/guide/platforms/win8/index.html

I can either
A. Use the old path in docs `8.x`, `9.x`, and `dev`.
B. Copy the images to the new folder path.

**Comment by dblotsky** [comment]
@erisu you might want to take a look at this: https://github.com/apache/cordova-docs/blob/master/doc/redirects.md. If that wouldn't resolve this issue, then I think option B is good.

**Comment by erisu** [comment]
@dblotsky Also, I just found and believe this was the PR that made this change. https://github.com/apache/cordova-docs/pull/797

**Comment by dblotsky** [comment]
@erisu yep, it looks like the PR renamed paths, but didn't copy over images. Sounds like option B (copying images so that they're in both `win8` and `windows`) is the way to fix this.
